services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: bolt_user
      POSTGRES_PASSWORD: bolt_password
      POSTGRES_DB: bolt_buy
    ports:
      - "6378:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata: